### ISSUE TITLE
Missing “platform” block?

### ISSUE THREAD

**Issue by mtuan1812** [Tommrodrigues/homebridge-web-rgb#3]
Hi there, 
I’ve build the corresponding ESP8266 NodeMCU server and it’s up and running. Installed the the homebridge-web-rgb plugin as well. But when I tried to edit my config.json, homebridge config UI X won’t let me save and exit as I was missing a platform block that was not also found on your example config. I’ve added the platform line and tried different combinations , still no hope as my hb does not recognise it and send SIGTERM to bootloop the instance. Any help will be appreciated!

"accessories": [
    {
        "accessory": "HTTP-RGB",
        "name": "RGB Strip",
        "apiroute": "http://rgb.local",
        "platform": "HTTP-RGB"
    }
]

**Comment by phenotypic** [comment]
The `config.json` snipped included in this repository simply outlines the core fields required to initialise the plugin, and which section they should be in - `accessories` in this case.

You should refer to the homebridge [`config-sample.json`](https://github.com/homebridge/homebridge/blob/master/config-sample.json) for a complete example of a `config.json` file.

**Comment by mtuan1812** [comment]
Thanks for your help!
