### ISSUE TITLE
Causing continuous homebridge reboots

### ISSUE THREAD

**Issue by cjastennett** [Tommrodrigues/homebridge-web-rgb#4]
Hi, with recent updates to Homebrige, this plugin seems broken. It was throwing up errors in json that crashed homebridge repeatably, sending it into an endless loop of reboots, The only way to resolve was to remove the code from the config file. Is anyone else having this issue? Thanks

**Comment by phenotypic** [comment]
Hi there, I can confirm that on the latest version of this plugin, `homebridge`, and `node` the plugin seems to work as expected.

Please could you include a copy of your `config.json` along with any errors you are receiving?
